[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["nexscribe*"]

[project]
name = "nexscribe"
version = "0.3.1"
description = "NeXScribe"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "rich>=15.0.0",
    "rttc>=1.0.6",
    "type-check>=0.1.8",
]

[dependency-groups]
dev = [
    "nexscribe",
    "mypy>=2.1.0",
    "pylint>=4.0.6",
    "pyright>=1.1.410",
    "pytest>=9.1.0",
    "ruff>=0.15.19",
]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
nexscribe = { workspace = true }
