exclude = [
    ".git",
    ".github",
    ".venv",
    ".vscode",
    "build",
    "*.egg-info",
    "**/__pycache__",
]
indent-width = 4
line-length = 160

[lint]
ignore = ["E701"]
unfixable = ["E701"]

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = true
