"""
This type stub file was generated by pyright.
"""

from .primitives import Chain
from typing import Sequence

"""
This type stub file was generated by pyright.
"""
def sequence_check(seq: Sequence, *args: type, chain: Chain) -> bool:
    ...

def set_check(s: set, typ: type, *, chain: Chain) -> bool:
    ...

def dict_check(d: dict, key_type: type, value_type: type = ..., *, chain: Chain) -> bool:
    ...

def no_check(item, *args: type, chain: Chain) -> bool:
    ...

