"""
This type stub file was generated by pyright.
"""

from typing import Callable, NoReturn, TypeVar
from typing_extensions import Unpack
from .primitives import Chain

"""
This type stub file was generated by pyright.
"""
STRICT = ...
CHECK_MISSING_ATTR = ...
TypeChecker = Callable[[object, Unpack[list[type]]], None | NoReturn]
builtin_checks = ...
def __extract_hint__(obj):
    ...

def type_check(obj, t: type = ...) -> bool:
    ...

T = TypeVar("T")
def type_assert(obj, t: type[T] = ..., *, chain: Chain | None = ...) -> T:
    ...

def __type_assert__(obj, t: type, *, chain: Chain) -> None | NoReturn:
    ...

def type_guard(t: type):
    """
    ## Decorate classes or functions to enforce type checking

    ### Usage:

    1. Decorating classes - do not use parentheses
    ```
    @type_guard
    class C(list[int]):
        pass
    ```

    2. Decorating functions - use type annotation pass type hint
    ```
    @type_guard
    def f(x) -> list[int]:
        return x
    ```

    3. Decorating functions - (alterative) use parenthesis to pass type hint
    ```
    @type_guard(list[int])
    def f(x):
        return x
    ```
    """
    ...

