"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

"""
This type stub file was generated by pyright.
"""
class Chain:
    def __init__(self, item: str | Chain.Attr | Chain.Key, parent: Chain = ...) -> None:
        ...
    
    def __call__(self, el: str | Attr | Key):
        ...
    
    def __iter__(self):
        ...
    
    @dataclass
    class Key:
        key: str | int | float | bool | None
        def __str__(self) -> str:
            ...
        
    
    
    @dataclass
    class Attr:
        attr: str
        def __str__(self) -> str:
            ...
        
    
    


class TypeCheckError(TypeError):
    value: object
    type_to_check: type
    def __init__(self, chain: Chain, expected: list[type], got: object) -> None:
        ...
    
    @property
    def result(self):
        ...
    


@dataclass
class TypeCheckResult:
    value: object
    type_to_check: type
    passed: bool
    reason: str | None
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __bool__(self) -> bool:
        ...
    
    def __eq__(self, value) -> bool:
        ...
    
    def __neq__(self, value):
        ...
    


