"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class TransparentProxy:
    """
    Hijacks _GenericAlias.__call__() so we can do stuff before and after the call
    """
    def __init__(self, cls: type) -> None:
        ...
    
    def __call__(self, *args, **kwargs):
        ...
    
    def __getattr__(self, key):
        ...
    
    def __setattr__(self, key, value):
        ...
    
    def __repr__(self):
        ...
    
    def __str__(self) -> str:
        ...
    
    def __setitem__(self, key, value):
        ...
    
    def __getitem__(self, key):
        ...
    
    def __type__(self):
        ...
    


